### ISSUE TITLE
Maximum Size of the payload in the datachannel?

### ISSUE THREAD

**Issue by mukesh-2538** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#119]
What is the maximum size of the payload which cant be sent over the datachannel. Is there an option to increase of decrease this limit?

**Comment by niyatim23** [comment]
Hi, thank you for your question. The SDK does not enforce any limits on the payload size for data channels as such because the specs don't mention anything about it. This limit is dictated by the browsers mainly. `usrsctp` is used by Chromium and its default limit is 256KB. Ideally, 16KB is a good data size. but [this article](https://lgrahl.de/articles/demystifying-webrtc-dc-size-limit.html) will be useful in determining the limits. 

Closing assuming answered. Feel free to reopen in case you have any other questions
