### ISSUE TITLE
[QUESTION] Connecting an existing KVS as master to signaling channel

### ISSUE THREAD

**Issue by michaelabela** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#120]
Hello! I've been messing around with this repo and have things working with connecting my local webcam as master to my signaling channel. I was wondering if there would be a way to connect an existing Kinesis Video Stream as master to the channel? I thought it could be done using [the GetMedia API](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_GetMedia.html) but I'm not quite sure how to work with the chunked stream data that comes back from that request. I may also be thinking about the pipeline incorrectly. I basically have an rtmp livestream that I am piping into kinesis video streams and I want to be able to play it back live using WebRTC in a web application. Any guidance would be super appreciated!

**Comment by disa6302** [comment]
@michaelabela , 

WebRTC SDKs alone might not be the right SDK for this use case. WebRTC does not store any media, it is a simple peer to peer connection, this means, it involves media exchange between the master and viewer and then each peer can use the media based on the use case. I would suggest looking at our producer SDKs because that enables ingesting fragments which you can get using GetMedia on the consumer end to get the fragments, and tie those fragments with WebRTC service to stream on Signaling channel.
