### ISSUE TITLE
[Question] Robust mechanism for reconnecting to master?

### ISSUE THREAD

**Issue by atyshka** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#121]
This SDK works great, but one issue I'm trying to figure out is how a viewer can automatically reconnect if the master is taken offline and restarted. I'm aware of how to detect a disconnect, using pc.connectionState, but I'm unsure of how to re-establish the connection. Could any examples be provided which would effectively handle this scenario?

**Comment by MushMal** [comment]
@atyshka you are referring to the RTP connection. The samples we have do not demonstrate the re-connection bur rather detection. We have a state change listener that cleans up sessions. An actual application could in fact detect the disconnect and retry the high-level scenario. This is not something that the sample does as it tries to strike a balance between the readability and functionality but this is certainly something that a target application could do. The main difficulty is that there is no good way of telling whether the other peer is "gone" due to network/reboot or simply decided to stop the streaming session

**Comment by disa6302** [comment]
Closing based on tag.
