### ISSUE TITLE
Limitation on number of viewers for group video chat

### ISSUE THREAD

**Issue by baj84** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#125]
We are looking for a way to allow for a group video chat of hundreds of users simultaneously.

Is this something that Kinesis would allow us to do? I read that there is a maximum of 10 connected viewers.

We are currently using Twilio that has a hard 50 participant limit.

Thanks!

**Comment by umarF** [comment]
Well I wanted to have channels with possibility to have 250 viewers but AWS allocated only 30 for now.
It is a soft limit but it can be increased based on use case.
What they state is the following:

> "The service team informed that Kinesis Video Streams WebRTC is not suitable for building applications that require multiple viewers because it only support Peer-to-Peer streaming which does not scale to a multi viewer scenario."


This basically becomes a dead end for me, I am using openvidu pro but in order to make some custom solution, there needs  to be flexibly of using N number of viewers per channel. They should look into it seriously otherwise there is not much use case for this feature apart from streaming from security cameras or 1 to 1 meeting.

**Comment by niyatim23** [comment]
Closing assuming answered, feel free to reopen in case of any further questions/issues.
