### ISSUE TITLE
Can't import the named export 'CryptoOps' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by puya91** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#275]
I am trying to update MSAL library (@azure/msal-browser) in my react app to v3.x (specifically from 2.14.2 to 3.2.0) but gives me this error after npm start:

./node_modules/@azure/msal-browser/dist/crypto/SignedHttpRequest.mjs Can't import the named export 'CryptoOps' from non EcmaScript module (only default export is available)

How can I fix this problem?

The reason why I want to update my MSAL library: Since the latest update of Google Chrome my Teams web app project shows a login popup for any API calls. It shows a popup every time for a second, verifies by itself, and goes away. I can see that my Local Storage is empty and clientIds are not already saved.

After updating to @azure/msal-browser@3.2.0 I expected to resolve my problem with the popup shown in my Teams web app. However, I have a problem executing the app. It gives me the compile error I mentioned above.

**Comment by sirknightj** [comment]
Hi @puya91, our SDK don't use `@azure/msal-browser` in our `package.json` or `package-lock.json`.
Please reach out to the authors of that dependency, which looks to be https://github.com/AzureAD/microsoft-authentication-library-for-js. 

Note: I see in their readme that there's a migration guide available since you're moving from 2.x to 3.x: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v2-migration.md, might be worth looking over that.

Please reach out if you are running into any other issues with Kinesis Video Streams with WebRTC!
