### ISSUE TITLE
webRTC SDK reConnection question

### ISSUE THREAD

**Issue by jiangjunzailushang** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#70]
After the viewer and the master successfully establish a connection, the network status of one side is poor (Even disconnect the network for a short time), does the webRTC SDK has a reconnection mechanism, and how long can it be reconnected?
Environment:
Master in browser and use sdk-js, viewer use sdk-c.

**Comment by lherman-cs** [comment]
@jiangjunzailushang yes, since our JS SDK only provides signaling, you can use [ice restart](https://developer.mozilla.org/en-US/docs/Web/API/RTCOfferOptions/iceRestart). However, you need to be careful with browser compatibility, Chromium based browsers support this well but I'm not sure with other browsers or even old chromium based browsers.

For the viewer, there shouldn't be an issue, we have recently added this, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/457.

Also, there was a similar issue about this. You might want to also check this out, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/issues/65.

**Comment by lherman-cs** [comment]
Due to staleness and the question is related to browser APIs. I'll close this issue. Please feel free to reopen if you need further assistance.
