### ISSUE TITLE
How to change Camera from Master in KVS

### ISSUE THREAD

**Issue by thasin96** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#71]
I have used WebRTC Sample Demo. It works really well in my machine. I would like to modify a bit further. in this process, I want to change camera to be streamed. I want to start streaming from a camera which is connected(wired or wireless) to my machine instead of my webcam. Is it possible? Or it would be better If I have option like streaming from an RTSP or HLS. Any hint would be Appreciable.

**Comment by lherman-cs** [comment]
@thasin96 yes, this is possible. What you need to do is simply enumerating the connected devices using, https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices. Then, you can find the device that you're interested in, and extract the device id. Later, when you call `getUserMedia`, make sure that you specify the device id, https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints.

**Comment by lherman-cs** [comment]
Since the issue has gone stalled, I'll mark this as resolved. Please feel free to reopen it for further assistance!

**Comment by mhaboali** [comment]
Hi @lherman-cs 

Could you explain how can I read images from a folder and upload it from one device to a Kinesis Signaling channel?

Actually, the use case exactly is an autonomous mobile robot and I'm trying to stream the video data to AWS Kinesis Signaling channel but I'm not able, so I'm thinking to use rosjs with this sdk to stream the data to the signaling channel.

Hope you'll be able to help with this use case.

**Comment by MushMal** [comment]
@mhaboali signaling channel is used for signaling and not data or media transfer. Perhaps you want to cut a new issue and detail your scenario. Take a look at the samples. Also, not sure what you mean by send images. Do you have your encoded video frames on the drive somewhere? Is this similar to the master sample application scenario from the Embedded WebRTC C SDK?

**Comment by mhaboali** [comment]
Thanks, @MushMal for the explanation!

Yeah, I'm looking for signaling the robot's video stream to be viewed in realtime from the user's side. I'm trying to do exactly what [this pkg](https://github.com/aws-robotics/kinesisvideo-ros1) does but this pkg works only with the normal Kinesis Streams not-WebRTC and it has around 4 seconds latency.

Yeah, I've checked that WebRTC C-sdk but I can't run this example with ROS which uses C++ and OOP stuff, so my idea is to use this js-sdk instead of c-sdk.

**Comment by mhaboali** [comment]
And for the encoding, I'm using [this pkg](https://github.com/aws-robotics/kinesisvideo-encoder-ros1)

**Comment by MushMal** [comment]
The issue is that JS solution is not really an implementation of a WebRTC - it's an implementation of a signaling with the built-in WebRTC so you might not be able to access the media pipeline.

You could think about using data channel to send your stream but then the question is whether you want to build all custom solution afteral. Anyway, this issue is already closed and is irrelevant to your case. Please do some research and cut more targeted issues to get more help

**Comment by mhaboali** [comment]
Ok got what you mean, I thought it's related because it's about changing the camera source. Alright, I'm opening a new issue as suggested.

Thanks for your help/time :)
