### ISSUE TITLE
ScreenShare Option in Conference Call

### ISSUE THREAD

**Issue by naveedaziz** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#82]
Dear, does kinesis webrtc support ScreenShare option. I am creating a conference call solution over kinesis video stream and need to add screen share option for users. Thanks

**Comment by lherman-cs** [comment]
Yes, since we only use browser APIs to get the video/audio streams, you can get this from getDisplayMedia, https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia.

You just need to replace the line below with getDisplayMedia:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/examples/master.js#L111
