### ISSUE TITLE
How to extend the signaling channel  connection duration limit - 1 hour (hard) 

### ISSUE THREAD

**Issue by satvatdevaws** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#97]
We are using the webrtc in our application to monitor the logged in users of our portal through their web cam through the signaling channel. Bu the signaling channel connection duration limit is limited to - 1 hour (hard). How do i extend my connection duration to 2 hours (120 minutes) or more.

**Comment by cesarpachon** [comment]
hi I am also interested in this question

**Comment by MushMal** [comment]
Hello, we considered various time ranges for the connection duration and gravitated towards the default. NOTE: This is not a set duration and might change. The more important question to ask is why your application needs a two hour duration limit at all? I would strongly recommend not basing your application design on any limits. Your application should respond to disconnection and attempt to reconnect instead of "knowing" anything about the duration of the signaling connection.

NOTE: The duration does not apply to the actual streaming session once the SDPs are exchanged and the transceivers are sending/receiving data.

Closing this for now
